version: '2'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=school
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --explicit_defaults_for_timestamp --event-scheduler=1